# Generated by Django 5.2.8 on 2025-11-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventoryrecord_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='current_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryrecord',
            unique_together={('document_type', 'document_number', 'product', 'batch', 'cost_center')},
        ),
    ]
