# Generated by Django 5.2.8 on 2025-11-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_current_quantity_product_current_unit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=128)),
                ('initial_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('initial_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
