# Generated by Django 5.2.8 on 2026-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventoryrecord_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_i_product_b09a08_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['product', 'warehouse', 'date'], name='inventory_i_product_277c90_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['date'], name='inventory_i_date_2c3613_idx'),
        ),
    ]
