# Generated by Django 5.2.8 on 2026-02-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryrecord',
            unique_together={('document_type', 'document_number', 'product', 'cost_center', 'date', 'warehouse', 'quantity')},
        ),
    ]
