# Generated by Django 5.2.8 on 2026-02-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventoryrecord_unique_together_add_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryrecord',
            unique_together={('document_type', 'document_number', 'product', 'cost_center', 'date', 'warehouse')},
        ),
    ]
