# Generated by Django 5.2.8 on 2026-02-26

import hashlib
from decimal import Decimal
from django.db import migrations, models


def _norm_sig(value):
    if value is None:
        return ''
    if isinstance(value, Decimal):
        if value == 0:
            return '0'
        return format(value.normalize(), 'f')
    raw = str(value).strip()
    if raw.lower() in ('nan', 'none', 'nat'):
        return ''
    return raw


def _build_source_record_hash(*values):
    base = '|'.join(_norm_sig(v) for v in values).encode('utf-8')
    return hashlib.sha1(base).hexdigest()[:24]


def forward_fill_source_fields(apps, schema_editor):
    InventoryRecord = apps.get_model('inventory', 'InventoryRecord')

    batch = []
    batch_size = 2000

    for rec in InventoryRecord.objects.all().iterator(chunk_size=batch_size):
        source_document = f"{(rec.document_type or '').strip()}{(rec.document_number or '').strip()}".strip()
        if not source_document:
            source_document = f"LEGACY{rec.id}"

        rec.source_document = source_document
        rec.source_record = _build_source_record_hash(
            source_document,
            rec.product_id,
            rec.warehouse,
            rec.date,
            rec.quantity,
            rec.unit_cost,
            rec.total,
            rec.final_quantity,
            rec.cost_center,
            rec.category,
        )
        batch.append(rec)

        if len(batch) >= batch_size:
            InventoryRecord.objects.bulk_update(batch, ['source_document', 'source_record'])
            batch = []

    if batch:
        InventoryRecord.objects.bulk_update(batch, ['source_document', 'source_record'])


def backward_fill_source_fields(apps, schema_editor):
    InventoryRecord = apps.get_model('inventory', 'InventoryRecord')
    InventoryRecord.objects.all().update(source_document='', source_record='')


def add_source_columns_if_missing(apps, schema_editor):
    """
    Añade columnas solo si no existen (idempotente para esquemas parciales).
    """
    InventoryRecord = apps.get_model('inventory', 'InventoryRecord')
    table_name = InventoryRecord._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if 'source_document' not in existing_columns:
        source_document_field = models.CharField(blank=True, default='', max_length=128)
        source_document_field.set_attributes_from_name('source_document')
        schema_editor.add_field(InventoryRecord, source_document_field)

    if 'source_record' not in existing_columns:
        source_record_field = models.CharField(blank=True, default='', max_length=64)
        source_record_field.set_attributes_from_name('source_record')
        schema_editor.add_field(InventoryRecord, source_record_field)


def add_source_index_if_missing(apps, schema_editor):
    """
    Crea índice de source_document/source_record solo si aún no existe.
    """
    InventoryRecord = apps.get_model('inventory', 'InventoryRecord')
    table_name = InventoryRecord._meta.db_table
    index_name = 'inventory_i_source_doc_rec_idx'

    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, table_name
        )

    if index_name in constraints:
        return

    index = models.Index(
        fields=['source_document', 'source_record'],
        name=index_name,
    )
    schema_editor.add_index(InventoryRecord, index)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_revert_unique_together_remove_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='document_type',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_source_columns_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='inventoryrecord',
                    name='source_document',
                    field=models.CharField(blank=True, default='', max_length=128),
                ),
                migrations.AddField(
                    model_name='inventoryrecord',
                    name='source_record',
                    field=models.CharField(blank=True, default='', max_length=64),
                ),
            ],
        ),
        migrations.RunPython(forward_fill_source_fields, backward_fill_source_fields),
        migrations.AlterUniqueTogether(
            name='inventoryrecord',
            unique_together={
                ('source_document', 'source_record', 'product', 'cost_center', 'date', 'warehouse')
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_source_index_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='inventoryrecord',
                    index=models.Index(
                        fields=['source_document', 'source_record'],
                        name='inventory_i_source_doc_rec_idx',
                    ),
                ),
            ],
        ),
    ]
