# Generated by Django 5.2.8 on 2026-03-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_backfill_row_hash'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryrecord',
            name='inv_rec_product_date_idx',
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='row_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
