# Generated by Django 5.2.8 on 2026-03-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_spanish_database_views'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP VIEW IF EXISTS inventory_vw_movimientos_inventario",
                "DROP VIEW IF EXISTS inventory_vw_detalle_almacen",
                "DROP VIEW IF EXISTS inventory_vw_productos",
                "DROP VIEW IF EXISTS inventory_vw_lotes_importacion",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RenameIndex(
            model_name='inventoryrecord',
            new_name='inventario__product_00b285_idx',
            old_name='inventory_i_product_2f833d_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrecord',
            new_name='inventario__product_75623a_idx',
            old_name='inventory_i_product_b09a08_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrecord',
            new_name='inventario__product_1a8882_idx',
            old_name='inventory_i_product_277c90_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrecord',
            new_name='inventario__almacen_065fc3_idx',
            old_name='inventory_i_warehou_7662fa_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrecord',
            new_name='inventario__tipo_do_f42158_idx',
            old_name='inventory_i_documen_da83cf_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrecord',
            new_name='inventario__fecha_56f2eb_idx',
            old_name='inventory_i_date_2c3613_idx',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='checksum',
            field=models.CharField(blank=True, db_column='suma_verificacion', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='file_name',
            field=models.CharField(db_column='archivo', max_length=255),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='inventory_name',
            field=models.CharField(db_column='nombre_inventario', db_index=True, default='default', max_length=128),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='processed_at',
            field=models.DateTimeField(blank=True, db_column='procesado_en', null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='rows_imported',
            field=models.IntegerField(db_column='filas_importadas', default=0),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='rows_total',
            field=models.IntegerField(db_column='filas_totales', default=0),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_column='iniciado_en'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='batch',
            field=models.ForeignKey(db_column='lote_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.importbatch'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='category',
            field=models.CharField(blank=True, db_column='categoria', max_length=128),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='cost_center',
            field=models.CharField(blank=True, db_column='centro_costo', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='date',
            field=models.DateField(db_column='fecha'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='document_number',
            field=models.CharField(blank=True, db_column='numero_documento', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='document_type',
            field=models.CharField(blank=True, db_column='tipo_documento', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='final_quantity',
            field=models.DecimalField(blank=True, db_column='cantidad_final', decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='lote',
            field=models.CharField(blank=True, db_column='lote', max_length=64),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='product',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='quantity',
            field=models.DecimalField(db_column='cantidad', decimal_places=3, max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='row_hash',
            field=models.CharField(blank=True, db_column='hash_fila', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='source_document',
            field=models.CharField(blank=True, db_column='documento_origen', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='source_record',
            field=models.CharField(blank=True, db_column='registro_origen', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='total',
            field=models.DecimalField(db_column='valor_total', decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='unit_cost',
            field=models.DecimalField(db_column='costo_unitario', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='warehouse',
            field=models.CharField(db_column='almacen', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_column='codigo', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_quantity',
            field=models.DecimalField(blank=True, db_column='cantidad_actual', decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_unit_cost',
            field=models.DecimalField(blank=True, db_column='costo_unitario_actual', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(db_column='descripcion', max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(blank=True, db_column='grupo', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_balance',
            field=models.DecimalField(db_column='saldo_inicial', decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_unit_cost',
            field=models.DecimalField(db_column='costo_unitario_inicial', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_name',
            field=models.CharField(db_column='nombre_inventario', db_index=True, default='default', max_length=128),
        ),
        migrations.AlterField(
            model_name='warehousedetail',
            name='initial_quantity',
            field=models.DecimalField(db_column='cantidad_inicial', decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='warehousedetail',
            name='initial_value',
            field=models.DecimalField(db_column='valor_inicial', decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='warehousedetail',
            name='product',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='warehousedetail',
            name='warehouse',
            field=models.CharField(db_column='almacen', max_length=128),
        ),
        migrations.AlterModelTable(
            name='importbatch',
            table='inventario_lotes_importacion',
        ),
        migrations.AlterModelTable(
            name='inventoryrecord',
            table='inventario_movimientos',
        ),
        migrations.AlterModelTable(
            name='product',
            table='inventario_productos',
        ),
        migrations.AlterModelTable(
            name='warehousedetail',
            table='inventario_detalle_almacen',
        ),
        migrations.RunSQL(
            sql=[
                """
                CREATE OR REPLACE VIEW inventory_vw_lotes_importacion AS
                SELECT
                    b.id AS lote_id,
                    b.archivo AS archivo,
                    b.iniciado_en AS iniciado_en,
                    b.procesado_en AS procesado_en,
                    b.filas_totales AS filas_totales,
                    b.filas_importadas AS filas_importadas,
                    b.suma_verificacion AS checksum,
                    b.nombre_inventario AS nombre_inventario
                FROM inventario_lotes_importacion b
                """,
                """
                CREATE OR REPLACE VIEW inventory_vw_productos AS
                SELECT
                    p.id AS producto_id,
                    p.codigo AS codigo,
                    p.descripcion AS descripcion,
                    p.grupo AS grupo,
                    p.nombre_inventario AS nombre_inventario,
                    p.saldo_inicial AS saldo_inicial,
                    p.costo_unitario_inicial AS costo_unitario_inicial,
                    p.cantidad_actual AS cantidad_actual,
                    p.costo_unitario_actual AS costo_unitario_actual
                FROM inventario_productos p
                """,
                """
                CREATE OR REPLACE VIEW inventory_vw_detalle_almacen AS
                SELECT
                    wd.id AS detalle_id,
                    wd.producto_id AS producto_id,
                    wd.almacen AS almacen,
                    wd.cantidad_inicial AS cantidad_inicial,
                    wd.valor_inicial AS valor_inicial
                FROM inventario_detalle_almacen wd
                """,
                """
                CREATE OR REPLACE VIEW inventory_vw_movimientos_inventario AS
                SELECT
                    ir.id AS movimiento_id,
                    ir.lote_id AS lote_id,
                    ib.archivo AS archivo_lote,
                    ir.producto_id AS producto_id,
                    p.codigo AS codigo_producto,
                    p.descripcion AS descripcion_producto,
                    ir.almacen AS almacen,
                    ir.fecha AS fecha,
                    ir.tipo_documento AS tipo_documento,
                    ir.numero_documento AS numero_documento,
                    ir.documento_origen AS documento_origen,
                    ir.registro_origen AS registro_origen,
                    ir.cantidad AS cantidad,
                    ir.costo_unitario AS costo_unitario,
                    ir.valor_total AS valor_total,
                    ir.categoria AS categoria,
                    ir.lote AS lote,
                    ir.cantidad_final AS cantidad_final,
                    ir.centro_costo AS centro_costo,
                    ir.hash_fila AS hash_fila
                FROM inventario_movimientos ir
                INNER JOIN inventario_productos p
                    ON p.id = ir.producto_id
                LEFT JOIN inventario_lotes_importacion ib
                    ON ib.id = ir.lote_id
                """,
            ],
            reverse_sql=[
                "DROP VIEW IF EXISTS inventory_vw_movimientos_inventario",
                "DROP VIEW IF EXISTS inventory_vw_detalle_almacen",
                "DROP VIEW IF EXISTS inventory_vw_productos",
                "DROP VIEW IF EXISTS inventory_vw_lotes_importacion",
            ],
        ),
    ]
