# Generated by Django 5.2.8 on 2026-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_remove_inventoryrecord_inventario__product_00b285_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='nombre_inventario',
            field=models.CharField(db_column='nombre_inventario', db_index=True, default='Por defecto', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre_inventario',
            field=models.CharField(db_column='nombre_inventario', db_index=True, default='Por defecto', max_length=128),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['nombre_inventario', 'procesado_en'], name='inv_lote_inv_proc_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['nombre_inventario', 'iniciado_en'], name='inv_lote_inv_init_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['categoria', 'fecha'], name='inventario__cat_fec_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['producto', 'almacen', 'cantidad_final'], name='inventario__prod_wh_fi_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nombre_inventario', 'grupo'], name='inv_prod_inv_grp_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nombre_inventario', 'codigo'], name='inv_prod_inv_cod_idx'),
        ),
    ]
